// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp09qOLYC40v5SlLi2kyRar6ns9Edp--M',
    appId: '1:919536353657:web:79ebe3077a4ae3bd8d2fa8',
    messagingSenderId: '919536353657',
    projectId: 'chatapp-bbfca',
    authDomain: 'chatapp-bbfca.firebaseapp.com',
    storageBucket: 'chatapp-bbfca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnWSsUarUvfa_Xve_mb2Wh9KH4dHSgke4',
    appId: '1:919536353657:android:ab807a21a1bf74498d2fa8',
    messagingSenderId: '919536353657',
    projectId: 'chatapp-bbfca',
    storageBucket: 'chatapp-bbfca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9SJC0R9shETRqbKGtv10uNyUwA0wNQ0E',
    appId: '1:919536353657:ios:3f1cd8aee099d9328d2fa8',
    messagingSenderId: '919536353657',
    projectId: 'chatapp-bbfca',
    storageBucket: 'chatapp-bbfca.appspot.com',
    iosBundleId: 'com.example.advancedlessons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9SJC0R9shETRqbKGtv10uNyUwA0wNQ0E',
    appId: '1:919536353657:ios:559f359cc568aaaa8d2fa8',
    messagingSenderId: '919536353657',
    projectId: 'chatapp-bbfca',
    storageBucket: 'chatapp-bbfca.appspot.com',
    iosBundleId: 'com.example.advancedlessons.RunnerTests',
  );
}
